// Component

// Add any installation instructions

== Background
Docker CE is deployed to host containers that provide a variety of services some of which require multiple container instances. 

== Prerequisites
* In Satellite Custom product repository hosting Docker Packages (Docker CE)
* Custom product repository is enabled for this host
* Certificate Authority to issue certificates for secure connections

.Docker Host Hardware Requirements
[cols="2s,5a",options=header]
|===
|Hardware
|Requirement

| CPU
| 2 with 2 sockets

| Memory
| 64 GB

| Storage
|
* Disk 1: 120 GB (OS)
* Disk 2: 100 GB (DOCKER)
* Disk 3: 300 GB (APPDATA)
|===

== Deploy and Configure VM
This system will be deployed and hosted on a virtualization platform as a virtual machine (VM). It is recommended that this system be deployed using Red Hat Satelite and automation but it can be deployed manually through use of processes native to the virtualization platform. A manual deployment should not present issues as long as all previously noted prerequisites are properly implemented. 

Before proceeding ensure the following tasks are completed:

- Resource requirements are met
- Required RHEL 9 Repositories are available
- Required Installation software is available


NOTE: If Satellite will be used to access docker RPMs, ensure that the Satellite registration for this system include activation keys allow the system to be properly updated as well as provide access to these RPMs.

== Configure Docker Storage
include::docker_host/storage.adoc[]

== Certificates for Docker Host
. Keys and a certificate signing request (CSR) will need to be generated by the host. * See Appendix: <<Create SSL Certificate Signing Request>>

== Docker Host Installation
. Ensure the system has access to the Docker RPMs. This can be accomplished via one of the two steps that follow:
- (OPTIONAL) This step assumes there is a satellite server online with the Docker RPMs. Ensure the host is registered to satellite using an activation key that is configured with the appropriate content views that will allow access to the Docker RPMs
- (OPTIONAL) If there isn't a satellite server configured hosting the Docker RPMs, enable Docker CE Custom Repository
+

[source,bash]
----
subscription-manager repos --enable <DOCKER CE CUSTOM REPOSITORY>
----

. Install Docker CE
+

[source,bash]
----
dnf install docker-ce docker-scan-plugin docker-ce-cli docker-ce-rootless-extras docker-buildx-plugin docker-compose-plugin -y
----

. Start Docker and set it to start at boot
+

[source,bash]
----
systemctl enable --now docker
----

